Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -20,13 +20,42 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: 3.11
-      - name: estoy en
-        run: ls
       - name: Install dependencies
         run: |
           pip install -r requirements.txt
-          pip install pytest
+          pip install pytest coverage pytest-cov
         working-directory: ./app
+      - name: "Run Pytest"
+        if: always()
+        run: |
+          set +e
+          pytest -v --cov --cov-report=json --cov-report=html --cov-report=term
+          retVal=$?
+          if [ $retVal -ne 0 ]; then
+            echo "PYTEST=FAIL" >> $GITHUB_ENV
+          else
+            echo "PYTEST=PASS" >> $GITHUB_ENV
+          fi
+          exit $retVal
+      - name: "Export summary"
+        if: always()
+        run: |
+          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
+          export STMTS=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['num_statements'])")
+          echo "total=$TOTAL" >> $GITHUB_ENV
+          echo "stmts=$STMTS" >> $GITHUB_ENV
+          echo "### Tests" >> $GITHUB_STEP_SUMMARY
+          echo "#### Python: ${{ env.PYTEST }}" >> $GITHUB_STEP_SUMMARY
+          echo "### Coverage" >> $GITHUB_STEP_SUMMARY
+          echo "#### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
+          echo "#### Statements: ${STMTS}" >> $GITHUB_STEP_SUMMARY
+
+      - name: Upload Coverage HTML Report
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: coverage-report
+          path: htmlcov
       # - name: "Check out the repo"
       #   uses: "actions/checkout@v3"
 
